### PR TITLE
sort lavatories for baby changing

### PR DESCRIPTION
**Pull request by SHoen**
This PR provides ( feature to get the lavatories with baby changing on top of the list. 

I added a baby changing button to the menu bar close to the location button.
It modifies the sorting of the list, if activated all lavatories with baby changing in the search radius will displayed at the top of the list. 
State is stored and can also be modified in the preferences. 

Let me know what you think. 

Best,
Steffen

### CODE REVIEW

**Comment by SHoen** [comment]
1. Good point! I just searched a way to manage the state and inject it into the SQLite helper. Probably there is a better way of doing this as well. 
2. Yes I also thought an additional button is too much. I like the long click toggle, because I think its practical not to click though a "array of sorting functions". Long click might need some explanation though.  Probably switch "Preferred sorting" in Preferences? 

Btw. I just figured out that the baby changing button is not light enough in the dark mode.

**Comment by woheller69** [comment]
dark mode is fixed with android:fillColor="#FFFFFF"
I pushed a commit few min ago.

But maybe you are right and the simplest approach is a Sorting Priority in preferences and remove the button from the menu:

"Sorting priority":
1) None
2) Baby changing
3) Wheel chair

**Comment by woheller69** [comment]
Are you going to work on it and update the PR?

**Comment by SHoen** [comment]
Yes I will update the PR when I have some spare time :)

**Comment by woheller69** [comment]
I changed the SwitchPreference to a ListPreference with options
None
Baby changing
Wheelchair

If you like it I think it can be merged

**Comment by SHoen** [comment]
Yes I am fine with it.

**Comment by woheller69** [comment]
Thanks for contributing :-)

**Comment by SHoen** [comment]
I have to thank for this nice collaboration and your openness.

**Pull request merged**
